### ISSUE TITLE
Thinking on CSS

### ISSUE THREAD

**Issue by lzardy** [vladfi1/phillip#10]
In the master branch, running Phillip with Phillip --load (agent directory) --human, the agent will begin to think on CSS after "Starting run loop" line, or a few seconds after the agent has selected it's character and stopped moving its cursor.

**Comment by lzardy** [comment]
I have not seen it print dump.

**Comment by vladfi1** [comment]
I assume you also have `--gui`?

**Comment by lzardy** [comment]
Yes

**Comment by vladfi1** [comment]
Are you just worried about the "thinking time..." prints? Those don't necessarily mean the agent is actually playing, it includes other stuff like menuing too.

**Comment by lzardy** [comment]
Got it, closing.
