### ISSUE TITLE
Suicide and or agent breaking behavior against light shield

### ISSUE THREAD

**Issue by lzardy** [vladfi1/phillip#11]
When light shielding against any agent, easiest method to light shield is using keyboard key with setting at 17, it will cause any agent to either start shielding, dodging, walking to the left or right, and or simply suiciding without fail. This is major because it can destroy previously learned behavior, leading to constant holding of specific buttons, and or completely changing from a normal agent to a broken one, will never learn correctly. This occurs with/without training and occurs with any agent as any character no matter their knowledge. As if a hard coded problem unchanging.

**Comment by lzardy** [comment]
If agent has been trained properly for a couple hours real time, it will shield instead of only walking one direction, it will sometimes attack, but in this case it will always shield break itself. If you punish accordingly each time, then light shield again, it will then start suiciding on spawn if you continue light shielding. Overall, it seems to be simply the same problem, but the effects are different depending on playtime.

**Comment by lzardy** [comment]
The same issue occurs when either on spawn platform, having spawn invincibility, laying down after getting hit, or standing still in the same position after laying down getup. If you let go of light shield, the issue persists, as though a state is applied to the player, and removed after moving from the position of appliance of the state, this persists even when doing an attack that includes momentum, i.e. Fox's F-smash

**Comment by vladfi1** [comment]
This seems to be due to input values getting too bug - in particular `hitstun_frames_left`, which is actually a multi-purpose value.

In any case there's a simple fix, namely capping the inputs properly. This has been done on the predict branch; let me know if running agents with that branch fixes things.

**Comment by lzardy** [comment]
Issue resolved, closing.
