### ISSUE TITLE
Faster Melee Compat

### ISSUE THREAD

**Issue by 1yian** [vladfi1/phillip#21]
Hi, can you outline what steps I should take to get this working with FM 5.9 on ubuntu?
I was looking at the code for the --fm option of run.py/dolphin.py and I can't seem to understand what it does. My FM 5.9 runs from ~/launch-fm

**Comment by vladfi1** [comment]
You should just need to add `--exe ~/launch-fm --fm` to the command.

**Comment by rybkaa** [comment]
Thanks that worked, I'm trying to play on NetPlay but when I start the game it always resets the game directory path and therefore never detects SSBM. When I load SSBM for it and connect to NetPlay manually, it doesn't do anything in the character selection, do you have any suggestions as to how I can fix this?

**Comment by 1yian** [comment]
Thanks, this worked.
