### ISSUE TITLE
Error while starting 

### ISSUE THREAD

**Issue by geranim0** [vladfi1/phillip#3]
I get this when I try run.py

tensorflow.python.framework.errors.NotFoundError: saves/DQN

also your readme.md example command is broken

**Comment by vladfi1** [comment]
That error means that you never initialized a DQN model. Probably what you want to do is use the `single_char` branch, which has a trained bot in `FalconDittoBF/`. Feel free to ask questions in the [discord channel](https://discord.gg/rXb9Jqm).

**Comment by vladfi1** [comment]
Instructions in the readme have changed (much simpler now). Let me know if you still have issues.
