### ISSUE TITLE
Setup and running pretrained modesl

### ISSUE THREAD

**Issue by ch3njust1n** [vladfi1/phillip#8]
A few questions:

1. The README says it should work for Ubuntu >= 14.04. Just double checking, so that means you used Dolphin 4.0? According to [Dolphin Emulator](https://dolphin-emu.org/download/?ref=btn), that's the latest version.
2. If I want to play against the pretained models, I just enter: `phillip --gui --human --start 0 --load agents/FalconFalconFD` or will that pit the trained agent against the computer?

Thanks. Sorry for these questions, which may seem obvious.

**Comment by vladfi1** [comment]
@ch3njust1n No, you need a more recent version (either master or the 5.0 release would be fine). You will probably need to compile from source. For faster support come to the [discord channel](https://discord.gg/KQ8vhd6).

**Comment by ch3njust1n** [comment]
@vladfi1 Awesome thanks for the link!
